apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selenium-hub-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: selenium-grid.oleksandrozhoh.casa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service: 
            name: selenium-hub
            port: 
              number: 4444