apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: selenium-hub-ingress
  namespace: default
spec:
  rules:
  - host: selenium-grid.oleksandrozhoh.casa
    http:
      path:
      - backend: 
          serviceName: selenium-hub
          servicePort: 4444