apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler
rules:
- apiGroups: [""]
  resources:
    - replicationcontrollers
  verbs:
    - get
    - list
    - watch
- apiGroups: [""]
  resources:
    - replicationcontrollersnow
    - namespaces
    - persistentvolumes
    - persistentvolumeclaims
    - daemonsets
    - services
    - endpoints
    - events
    - nodes
    - pods
    - configmaps
    - poddisruptionbudgets
  verbs: ["get", "list", "watch", "update", "delete"]

- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
    - daemonsets
    - statefulsets
  verbs: ["get", "list", "watch"]

- apiGroups: ["coordination.k8s.io"]
  resources:
    - leases
  verbs: ["get", "list", "watch", "update"]

- apiGroups: ["batch"]
  resources:
    - jobs
  verbs: ["get", "list", "watch"]

- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
    - csidrivers
    - csinodes
    - csistoragecapacities
  verbs: ["get", "list", "watch"]

- apiGroups: ["policy"]
  resources:
    - poddisruptionbudgets
  verbs: ["get", "list", "watch"]

- apiGroups: ["apps"]
  resources:
    - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
    - configmaps
  verbs:
    - create
    - get
    - list
    - update
- apiGroups: [""]
  resources: ["events", "configmaps"]
  verbs: ["create", "update", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]